FROM alpine:3.20.3

WORKDIR /var/www/html/

RUN apk add --no-cache nginx && \
	mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.default && \
	adduser -Dg 'www' 'www'
	# chown -R www:www /run/nginx/ && \
	# chown -R www:www /usr/share/nginx/ && \
	# chown -R www:www /usr/lib/nginx/ && \
	# chown -R www:www /etc/nginx/ && \
	# chown -R www:www /var/lib/nginx/ && \
	# chown -R www:www /var/log/nginx/

COPY ./nginx.conf /etc/nginx/

EXPOSE 443

# USER www

CMD [ "nginx", "-g", "daemon off;" ]