FROM alpine:3.20.3

WORKDIR /www

RUN apk update && \
	apk add nginx && \
	adduser -D -g 'www' 'www' && \
	chown -R www:www /www && \
	chown -R www:www /var/lib/nginx

COPY ./nginx.conf /etc/nginx/
COPY ./index.html .

EXPOSE 443

CMD [ "nginx" ]